- hosts: 127.0.0.1
  connection: local
  tasks:
      - name: RENAME A FILE WITH OLD CONFIGURATIONS
        shell: mv interfaces interfaces.old # CREATE A BACKUP FILE FOR INTERFACES
        args:
               chdir: "/etc/network/" # PATH FOR INTERFACES

      - name: CREATE A NEW FILE CONFIGURATION
        file:
             path: "/etc/network/interfaces" # CREATE A NEW FILE CONFIGURATION FOR NETWORK INTERFACES
             state: touch

      - name: ADD NEW IP CONFIGURATION
        lineinfile:
             path: "/etc/network/interfaces" # PATH FOR EDITION
             state: present
             line: "{{ item }}" # WORD WRAP ON THE FILE
        with_items: 
             - '# First network interface:'
             - ''
             - 'auto enp0s3'
             - 'iface enp0s3 inet static'
             - 'address 10.0.2.30'
             - 'netmask 255.0.0.0'
             - 'gateway 10.0.2.1'
